name: Terraform Apply for AKS Demo

on:
  workflow_dispatch:

jobs:
  apply-terraform:
    name: Apply terraform files and kubernetes manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Azure CLI Setup and Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13.1"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: |
          terraform plan -var="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
                         -var="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
                         -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
                         -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
                         -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
